### ISSUE TITLE
How to match current date to dayID in readings_list?

### ISSUE THREAD

**Issue by AlwinEdwards** [jayarathina/Tamil-Catholic-Lectionary#4]
How to match current date to dayID in readings_list? i need to get reading list and feast code for particular day.

**Comment by jayarathina** [comment]
Can you please explain what you mean by particular day? Do you mean a particular date or a solemnity/feast/memory/op.memory or for something like Thursday of Second week of advent? Can you please give me an example `dayID` you have in mind.

P.S Please understand that this project is not even close from being complete (probably only 1% of the data is entered, that too with errors.) It has lots or maintenance to do and the DB is definitely is not normalized. I am currently working on it. Given my seminary schedule and other projects, It will take a very long time before it is suitable for any meaningful use. That was the reason I did not even add an MD file. (Now I have added it.)

**Comment by AlwinEdwards** [comment]
Sorry for that. i mean particular date. for example given date is 09-01-2019 (today date) But dayID in database is like CW03-Day5 in readings_list table. Thank you
--

**Comment by jayarathina** [comment]
Hi, I am really sorry for the late reply.

The logic to do that would be to use [Roman-Calendar](https://github.com/jayarathina/Roman-Calendar) to get current day-id and match it in DB.

But that and other functions will be added to the library very soon. The library is not yet complete yet. Once proper functions are added and [a release](https://github.com/jayarathina/Tamil-Catholic-Lectionary/releases) is done I will update the project. I am currently back to seminary where I do not have time to work on this project right now.

**Comment by jayarathina** [comment]
The logic is to us [Roman Calendar](https://github.com/jayarathina/Roman-Calendar) and get the day's key and use it to retrieve from `readings_list` table.

The library (and this project) is not yet ready. I am currently a bit busy with my studies. I will update the library once i have coded this and other logic. Thanks for your understanding.

**Comment by AlwinEdwards** [comment]
OK Thank You
